#!/bin/sh

sysresources="/etc/X11/xinit/.Xresources"
sysmodmap="/etc/X11/xinit/.Xmodmap"
userresources="$XDG_CONFIG_HOME/x11/xresources"
usermodmap="$XDG_CONFIG_HOME/x11/xmodmap"

# Change cursor to left pointer
xsetroot -cursor_name left_ptr &

# merge in defaults and keymaps
# [ -f $sysresources ] && xrdb -merge $sysresources
# [ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# # start some nice programs
# if [ -d /etc/X11/xinit/xinitrc.d ] ; then
#  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
#   [ -x "$f" ] && . "$f"
#  done
#  unset f
# fi

# Blue light filter
redshift &

# Pipewire
pipewire &
pipewire-pulse &
pipewire-media-session &

# sxhkd, picom, polybar, nitrogen, etc started in bspwmrc
exec bspwm
