#!/bin/sh

export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

SCRIPT_NAME="$(basename "$0")"

# Battery percentage at which to notify
WARNING_LEVEL=20
FULL_LEVEL=90
BATTERY_DISCHARGING="$(acpi --battery | \
    grep "Battery 0" | \
    grep -c "Discharging")"
BATTERY_LEVEL="$(acpi --battery | \
    grep "Battery 0" | \
    grep -P -o '[0-9]+(?=%)')"

# Use two files to store whether we've shown a notification or not (to prevent multiple notifications)
EMPTY_FILE="/tmp/battery-empty"
FULL_FILE="/tmp/battery-full"

# Reset notifications if the computer is charging/discharging
if [ "$BATTERY_DISCHARGING" -eq 1 ] && \
    [ -f "$FULL_FILE" ]; then
    rm "$FULL_FILE"
elif [ "$BATTERY_DISCHARGING" -eq 0 ] && \
    [ -f "$EMPTY_FILE" ]; then
    rm "$EMPTY_FILE"
fi

# If the battery is charging and is full (and has not shown notification yet)
if [ "$BATTERY_LEVEL" -ge "$FULL_LEVEL" ] && \
    [ "$BATTERY_DISCHARGING" -eq 0 ] && \
    [ ! -f "$FULL_FILE" ]; then
    notify-send -a "$SCRIPT_NAME" -u "normal" -i "battery-charging-100" -r 9991 \
        "Battery Charged"
    touch "$FULL_FILE"

# If the battery is low and is not charging (and has not shown notification yet)
elif [ "$BATTERY_LEVEL" -le "$WARNING_LEVEL" ] && \
    [ "$BATTERY_DISCHARGING" -eq 1 ] && \
    [ ! -f "$EMPTY_FILE" ]; then
    notify-send -a "$SCRIPT_NAME" -u critical -i battery-alert -r 9991 \
        "Low Battery" \
        "${BATTERY_LEVEL}% of battery remaining."
    touch "$EMPTY_FILE"
fi
