#!/bin/sh

# Script to change volume and notify using pamixer and dunst.

SCRIPT_NAME="$(basename "$0")"
ifinstalled "pamixer" || \
    exit

send_notification() {
    volume="$(pamixer --get-volume)"
    notify-send -a "$SCRIPT_NAME" -u "low" -i "volume-$1" -t 2000 -r "9993" \
       -h "int:value:$volume" \
       "Volume: ${volume}%"
}

muted() {
    notify-send -a "$SCRIPT_NAME" -u "low" -i "volume-mute" -t 2000 -r 9993 \
       "Muted"
}

case "$1" in
    "up")
        pamixer --unmute
        pamixer --increase 5 --allow-boost
        send_notification "$1"
        ;;
    "down")
        pamixer --decrease 5 --allow-boost
        if [ "$(pamixer --get-volume)" -gt 0 ]; then
            pamixer --unmute
            send_notification "$1"
        else
            pamixer --mute
            muted
        fi
        ;;
    "mute")
        pamixer --toggle-mute
        if "$(pamixer --get-mute)"; then
            muted
        else
            send_notification "up"
        fi
        ;;
    *)
        notify-send -a "$SCRIPT_NAME" -u "low" -i "bell" -t 2000 -r 9993 \
            "$SCRIPT_NAME: Error!" "Please specify the volume option (up, down, or mute)"
        ;;
esac
