#!/bin/sh

# Script to change brightness and notify using brillo and dunst.

SCRIPT_NAME="$(basename "$0")"
ifinstalled "brillo" || \
    exit

send_notification() {
    brightness=$(printf "%.0f\n" "$(brillo -G)")
    notify-send -a "$SCRIPT_NAME" -u "low" -i "brightness-$1" -t 2000 -r 9991 \
        -h "int:value:$brightness" \
        "Brightness: $brightness%"
}

case "$1" in
    "up")
        brillo -A 5 -q
        send_notification "$1"
        ;;
    "down")
        brillo -U 5 -q
        send_notification "$1"
        ;;
esac
