#!/bin/sh

send_notification() {
   volume=$(pamixer --get-volume)
   notify-send -a "change-volume" -u low -r "9993" -h int:value:"$volume" -i "volume-$1" "Volume: ${volume}%" -t 2000
}

muted() {
   notify-send -i volume-mute -a "change-volume" -t 2000 -r 9993 -u low "Muted"
}

case "$1" in
    up)
        pamixer --unmute
        pamixer --increase 5 --allow-boost
        send_notification "$1"
        ;;
    down)
        pamixer --decrease 5 --allow-boost
        if [ "$(pamixer --get-volume)" -gt 0 ]; then
            pamixer --unmute
            send_notification "$1"
        else
            pamixer --mute
            muted
        fi
        ;;
            mute)
        pamixer --toggle-mute
        if "$(pamixer --get-mute)"; then
            muted
        else
            send_notification up
        fi
        ;;
esac
