#!/bin/sh

###########################################################
#                    Autostart Scripts                    #
###########################################################

"${XDG_CONFIG_HOME}"/sxhkd/launch.sh &          # Hotkey daemon (sxhkd)
"${XDG_CONFIG_HOME}"/picom/launch.sh &          # Window compositor (picom)
"${XDG_CONFIG_HOME}"/polybar/launch.sh &        # Status bar (Polybar)
nitrogen --restore &                            # Wallpaper chooser (nitrogen)
killall -9 lxsession; lxsession &               # Session manager (lxsession)
killall -9 volumeicon; volumeicon &             # Volume icon in system tray
remapd &                                        # Keyboard remaps daemon
idle-handler &                                  # Auto lock and suspend
bsp-layout-start &                              # Set bspwm tiling layout
# pgrep -c ^bspswallow$ || bspswallow &           # Bspwm window swallowing

###########################################################
#                Screen / Workspaces Setup                #
###########################################################

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

##### Configuration #####

# source Xresources colors
[ -f "${XDG_DATA_HOME:-${HOME}/.local/share}/xcolors" ] ||
    gen-xcolors
. "${XDG_DATA_HOME:-${HOME}/.local/share}/xcolors"

# Customization
bspc config border_width                3
bspc config window_gap                  5
bspc config normal_border_color         "${color0}"
bspc config active_border_color         "${color1}"
bspc config focused_border_color        "${color3}"
bspc config presel_feedback_color       "${color2}"
bspc config borderless_monocle          true
bspc config gapless_monocle             true

# Workflow
bspc config focus_follows_pointer       true
bspc config split_ratio                 0.53

# Pointer
bspc config pointer_motion_interval     7ms
bspc config pointer_modifier mod4
## action: 1: left; 2: middle; 3: right
bspc config pointer_action1 move
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner

#########################################################
#                      BSPWM Rules                      #
#########################################################

bspc config external_rules_command \
    "${XDG_CONFIG_HOME:-$HOME/.config}/bspwm/bsp-external"

bspc rule -a Zathura                    state=tiled

bspc rule -a Guake                      state=floating
bspc rule -a KeePassXC                  state=floating
bspc rule -a rclone-browser             state=floating
bspc rule -a Xdialog                    state=floating
bspc rule -a Catfish                    state=floating
bspc rule -a Pavucontrol                state=floating

bspc rule -a mpv                        state=fullscreen

bspc rule -a Brave-browser              desktop='^2'
bspc rule -a code                       desktop='^3'
bspc rule -a zoom                       desktop='^4'
bspc rule -a whatsapp-nativefier-d40211 desktop='^5'

bspc rule -a Screenkey                  manage=off

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on

## TODO: Not working rules.
# bspc rule -a xev state=floating                     # no WM_CLASS.
# bspc rule -a motion_recorder state=floating         # line browser extension. idk.

######################
#        Misc        #
######################

# autostart-umar
# $HOME/.local/bin/autostart-umar
