#!/bin/sh

# source Xresources colors
[ -f "${XDG_DATA_HOME:-${HOME}/.local/share}/xcolors" ]
    gen-xcolors
. "${XDG_DATA_HOME:-${HOME}/.local/share}/xcolors"

dmenu-emoji |
    dmenu -i -nb "${color0}" -nf "${color3}" -sb "${color3}" -l 8 |
    awk '{print $1}' |
    xclip -selection clipboard
