#!/bin/sh

# A dmenu wrapper script for system functions.
export WM="bspwm"
case "$(readlink -f /sbin/init)" in
    *systemd*) ctl="systemctl" ;;
    *) ctl="loginctl" ;;
esac

# source Xresources colors
[ -f "${XDG_DATA_HOME:-${HOME}/.local/share}/xcolors" ] || \
    gen-xcolors
. "${XDG_DATA_HOME:-${HOME}/.local/share}/xcolors"

# dmenu configuration
dmenu_options="-i -nb "${color0}" -nf "${color3}" -sb "${color3}""
dmenu_prompt="dmenu $dmenu_options -p"
dmenu_prompt_msg="Action:"

# This function is needed if there are multiple instances of the window manager.
wmpid(){
    tree="$(pstree -ps $$)"
    tree="${tree#*"$WM"(}"
    echo "${tree%%)*}"
}

# action="$(printf "\
# 🔒 lock\n\
# 🚪 leave $WM\n
# ♻️ renew $WM\n
# 🐻 hibernate\n
# 🔃 reboot\n
# 🖥️ shutdown\n
# 💤 sleep\n
# 📺 display off\n\
#     " | dmenu -i -p 'Action: ')"

# case "$action" in
#     "♻️ renew $WM") bspc wm -r ;;
#     '🐻 hibernate') $ctl hibernate ;;
#     '💤 sleep') $ctl suspend-then-hibernate ;;
#     '🔃 reboot') $ctl reboot -i ;;
#     '🖥️ shutdown') $ctl poweroff -i ;;
#     '📺 display off') xset dpms force off ;;
#     *) exit 1 ;;
# esac

action="$(printf "\
 Power Off\n\
 Reboot\n\
 Suspend\n\
 Hibernate\n\
 Log Out\n\
 Lock\n\
󰶐 Display Off\n\
    " | ${dmenu_prompt} "$dmenu_prompt_msg")"

case "$action" in
    " Power Off") $ctl poweroff ;;
    " Reboot") $ctl reboot ;;
    " Suspend") $ctl suspend-then-hibernate ;;
    " Hibernate") $ctl  hibernate ;;
    # " Log Out") bspc quit ;;
    " Log Out") loginctl session-status | awk 'NR==1 {print $1}' | xargs loginctl terminate-session "$1" ;;
    " Lock") betterlockscreen -l ;;
    "󰶐 Display Off") xset dpms force off ;;
    *) exit 1 ;;
esac
