#!/bin/sh
# A dmenu binary prompt script
# Gives a dmenu prompt labeled with $1 to perform command $2
# for example:
# `./prompt "Do you want to shutdown?" "shutdown -h now""`

[ $(printf "No\nYes" | dmenu -i -nb "#0b060a" -nf "#f77416" -sb "#f77416" -p "$1") = "Yes" ] && $2
