#!/bin/sh
# A dmenu binary prompt script
# Gives a dmenu prompt labeled with $1 to perform command $2
# for example:
# `./prompt "Do you want to shutdown?" "shutdown -h now""`

# source Xresources colors
[ -f "${XDG_DATA_HOME:-${HOME}/.local/share}/xcolors" ] || gen-xcolors
. "${XDG_DATA_HOME:-${HOME}/.local/share}/xcolors"

[ "$(printf "No\nYes" | dmenu -i -nb "${color0}" -nf "${color3}" -sb "${color3}" -p "$1")" = "Yes" ] && "$2"
