#!/bin/sh

[ -f "${XDG_DATA_HOME:-${HOME}/.local/share}/xcolors" ] || gen-xcolors
. "${XDG_DATA_HOME:-${HOME}/.local/share}/xcolors"

while read -r file; do
    case "$1" in
        # "w"|"b") # set background / wallpaper
            # nitrogen --save --set-scaled "$file" &
            # ;;
        "w"|"b") # set background / wallpaper
            setbg "$file" &
            ;;
        "c") # copy to bm-dirs
            [ -z "$destdir" ] && destdir="$(sed "s/#.*$//;/^\s*$/d" "${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs" | awk '{print $2}' | dmenu -l 20 -i -nb ${color0} -nf ${color3} -sb ${color3} -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
            [ ! -d "$destdir" ] && notify-send -a "sxiv" "$destdir is not a directory, cancelled." && exit
            cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
            ;;
        "m") # move to bm-dirs
            [ -z "$destdir" ] && destdir="$(sed "s/#.*$//;/^\s*$/d" "${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs" | awk '{print $2}' | dmenu -l 20 -i -nb ${color0} -nf ${color3} -sb ${color3} -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
            [ ! -d "$destdir" ] && notify-send -a "sxiv" "$destdir is not a directory, cancelled." && exit
            rsync -urvP --remove-source-files --delete-after "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." &
        ;;
    "r") # rotate 90 degrees to the left
        convert -rotate 90 "$file" "$file"
        ;;
    "R") # rotate 90 degrees to the right
        convert -rotate -90 "$file" "$file"
        ;;
    "f") # flop (mirror)
        convert -flop "$file" "$file"
        ;;
    "F") # flip
        convert -flip "$file" "$file"
        ;;
    "y") # copy to clipboard
        printf "%s" "$file" | tr -d '\n' | xclip -selection clipboard &&
        notify-send -a "sxiv" -i "$(readlink -f "$file")" "$file copied to clipboard" & ;;
    "Y") # copy to clipboard
        readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
        notify-send -a "sxiv" -i "$(readlink -f "$file")" "$(readlink -f "$file") copied to clipboard" &
        ;;
    "d"|"t") # trash
        prompt "Trash $file?" "trash-put $file && notify-send -a "sxiv" $file trashed."
        ;;
    "D") # delete
        prompt "Permanently delete $file?" "rm $file && notify-send -a "sxiv" $file deleted."
        ;;
    "g") # open in gimp
        ifinstalled gimp && setsid -f gimp "$file"
        ;;
    "i") # mediainfo
        notify-send -a "sxiv" "File information" "$(mediainfo "$file" | sed "s/[ ]\+:/:/g;s/: /: <b>/;s/$/<\/b>/" | grep "<b>")"
        ;;
    esac
done
