#!/bin/sh

[ -f "${XDG_DATA_HOME:-${HOME}/.local/share}/xcolors" ] || gen-xcolors
. "${XDG_DATA_HOME:-${HOME}/.local/share}/xcolors"

while read -r file; do
    case "$1" in
        # "w"|"b")
            # nitrogen --save --set-scaled "$file" &
            # ;;
        "w"|"b")
            setbg "$file" &
            ;;
        "c")
            [ -z "$destdir" ] && destdir="$(sed "s/#.*$//;/^\s*$/d" "${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs" | awk '{print $2}' | dmenu -l 20 -i -nb ${color0} -nf ${color3} -sb ${color3} -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
            [ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
            cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
            ;;
        "m")
            [ -z "$destdir" ] && destdir="$(sed "s/#.*$//;/^\s*$/d" "${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs" | awk '{print $2}' | dmenu -l 20 -i -nb ${color0} -nf ${color3} -sb ${color3} -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
            [ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
            rsync -urvP --remove-source-files --delete-after "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." &
        ;;
    "r")
        convert -rotate 90 "$file" "$file"
        ;;
    "R")
        convert -rotate -90 "$file" "$file"
        ;;
    "f")
        convert -flop "$file" "$file"
        ;;
    "y")
        printf "%s" "$file" | tr -d '\n' | xclip -selection clipboard &&
        notify-send "$file copied to clipboard" & ;;
    "Y")
        readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
        notify-send "$(readlink -f "$file") copied to clipboard" &
        ;;
    "d"|"t")
        prompt "Trash $file?" "trash-put $file && notify-send $file trashed."
        ;;
    "D")
        prompt "Permanently delete $file?" "rm $file && notify-send $file deleted."
        ;;
    "g")
        ifinstalled gimp && setsid -f gimp "$file"
        ;;
    "i")
        notify-send "File information" "$(mediainfo "$file" | sed "s/[ ]\+:/:/g;s/: /: <b>/;s/$/<\/b>/" | grep "<b>")"
        ;;
    esac
done
