#!/bin/sh

# Script to cycle tiling layout on focused desktop using bsp-layout.

# Check if required program is installed
ifinstalled "bspwm" "bsp-layout" ||
    exit 1

# Set the layouts to cycle (CSV)
LAYOUTS="tall,wide,"

bsp-layout next --layouts "$LAYOUTS"
