#!/bin/sh

# Script to set all tiling layout for your bspwm desktop. Put this script on to
# your bspwmrc file to auto set all your desktop layouts.

# Check if bspwm and bsp-layout is installed
ifinstalled "bspwm" "bsp-layout" ||
    exit

# Set the default layout
# Available layouts: tiled, monocle, even, grid, rgrid, rtall, rwide, tall, wide
LAYOUT="tall"

# Check layoutrc file
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/bsp-layout/layoutrc" ] &&
    . "${XDG_CONFIG_HOME:-$HOME/.config}/bsp-layout/layoutrc"

# Use layoutrc `USE_NAME` variable if exists, otherwise default to 1
: "${USE_NAMES:=0}"
echo "$USE_NAMES"

# Get the desktop identifiers
if [ "$USE_NAMES" -eq 1 ]; then
    DESKTOPS="$(bspc query -D --names)"
else
    DESKTOPS="$(bspc query -D)"
fi

# Set all desktop layout
for desktop in $DESKTOPS; do
    bsp-layout set "$LAYOUT" "$desktop"
done
