#!/bin/sh

# This script does the following:
#    If given a file, set that as the new wallpaper.
#    If given a directory, choose random file in it.
#    If wal is installed, also generates a colorscheme.

SCRIPT_NAME="$(basename "$0")"
ifinstalled "nitrogen" "betterlockscreen" || \
    exit

# Location of link to wallpaper link.
background_location="${XDG_DATA_HOME:-$HOME/.local/share}/bg"

# Configuration files of applications that have their themes changed by pywal.
dunstconf="${XDG_CONFIG_HOME:-$HOME/.config}/dunst/dunstrc"
zathuraconf="${XDG_CONFIG_HOME:-$HOME/.config}/zathura/zathurarc"

true_location="$(readlink -f "$1")" &&
case "$(file --mime-type -bh "$true_location")" in
    image/* )
        ln -sf \
            "$(readlink -f "$1")" \
            "$background_location"
        notify-send -a "$SCRIPT_NAME" -i "$background_location" \
            "Changing wallpaper..."
        ;;
    inode/directory )
        ln -sf \
            "$(find "$true_location" \
            -iregex '.*.\(jpg\|jpeg\|png\|gif\)' \
            -type f | \
            shuf -n 1)" \
            "$background_location"
        notify-send -a "$SCRIPT_NAME" -i "$background_location" \
            "Random Wallpaper chosen."
        ;;
    *)
        notify-send -a "$SCRIPT_NAME" \
            "🖼️ Error" \
            "Not a valid image or directory."
        exit 1
        ;;
esac

# # If pywal is installed, use it.
# if command -v wal >/dev/null 2>&1 ; then
#     wal -n -i "$(readlink -f $background_location)" -o "${XDG_CONFIG_HOME:-$HOME/.config}/wal/postrun" >/dev/null 2>&1
# # If pywal is removed, return config files to normal.
# else
#     [ -f "$dunstconf.bak" ] && unlink "$dunstconf" && mv "$dunstconf.bak" "$dunstconf"
#     [ -f "$zathuraconf.bak" ] && unlink "$zathuraconf" && mv "$zathuraconf.bak" "$zathuraconf"
# fi

# change the background
nitrogen --save --set-zoom-fill "$background_location"
betterlockscreen -u "$background_location" --fx blur

# If running bspwm, hit the key to refresh the color scheme.
# pidof bspwm >/dev/null && bspc wm -r
